"use strict";

var GAME = GAME || {};

GAME.BASEWIDTH = 800;
GAME.BASEHEIGHT = 600;
GAME.RATIO = GAME.BASEWIDTH / GAME.BASEHEIGHT;

GAME.SCALE_X = 2.0;
GAME.SCALE_Y = 2.0;

GAME.DPAD_X_OFFSET = GAME.BASEWIDTH * 0.1;
GAME.DPAD_Y_OFFSET = GAME.BASEHEIGHT * 0.875;

GAME.PLAYER_SPEED = 3.0;

