"use strict";

var GAME = GAME || {};

GAME.BASEWIDTH = 800;
GAME.BASEHEIGHT = 600;
GAME.RATIO = GAME.BASEWIDTH / GAME.BASEHEIGHT;

GAME.SCALE_X = 2.0;
GAME.SCALE_Y = 2.0;

GAME.DPAD_X_OFFSET = GAME.BASEWIDTH * 0.1;
GAME.DPAD_Y_OFFSET = GAME.BASEHEIGHT * 0.875;

GAME.PLAYER_SPEED = 3.0;

GAME.ROOTTWOOVERTWO = 0.7071;
GAME.RADIANSTOANGLE = 57.29578;

GAME.DIRECTION = {};
GAME.DIRECTION.NONE = 0;
GAME.DIRECTION.UPLEFT = 1;
GAME.DIRECTION.UP = 2
GAME.DIRECTION.UPRIGHT = 3;
GAME.DIRECTION.LEFT = 4;
GAME.DIRECTION.RIGHT = 5;
GAME.DIRECTION.DOWNLEFT = 6;
GAME.DIRECTION.DOWN = 7;
GAME.DIRECTION.DOWNRIGHT = 8;

